# For GitHub user:
# github_username: "slack_member_id"
# For GitHub team:
# github_teamname: "slack_member_id"

manishapriya94: 'U014PTUCF45'

# Fellows
tdo95: 'U0457B11TLY'
ahn-nath: 'U043EMMAK9S'
rcmtcristian: 'U044N2XMGSC'
LoopFruits: 'U03A63J8U4V'
ericvennemeyer: 'U04354QA2K0'
sammychinedu2ky: 'U042T8UV7GF'
JoseEspinosaMachado: 'U043XLVG5R9'
