name: Cats

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cats:
    name: Cat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Action Cats
        uses: ruairidhwm/action-cats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
