name: Cats
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
