name: Cats

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cats:
    name: Cat
    runs-on: ubuntu-latest
    steps:
      - uses: ruairidhwm/action-cats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
