name: Cats

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: write

jobs:
  aCatForCreatingThePullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Action Cats
        uses: ruairidhwm/action-cats@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
