name: Measure issue timestamp

on:
  issues:
<<<<<<< HEAD
    types: [assigned]
=======
    types: [assigned, unlabeled]
    # repository:
    #   - ProgramEquity/amplify
  pull_request:
    types: [opened]
    branches:
      - main
>>>>>>> d7e6f34 (passport and sesson intialize for issue 617)

jobs:
  record_issue_timestamp:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
<<<<<<< HEAD
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Create branch linked to the issue
        id: create_branch
        run: |
          issue_number=$(echo "${{ github.event.issue.number }}")
          git checkout -b "issue-${issue_number}"
          echo "::set-output name=issue_branch::issue-${issue_number}"

      - name: Install
        run: npm install
        working-directory: ./roiScript

      - name: Run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: node ./roiScript/log-branch.mjs

      - name: Log Current Branch (debugging)
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Currently checked out branch: $current_branch"

      - name: Add Issue Timestamp To File
        working-directory: roiScript
        run: |
          issue_num=$(echo "${{ github.event.issue.number }}")
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          echo "$GITHUB_ACTOR, issue #${issue_num}: $timestamp" >> issue_timestamp.log

      - name: Commit Issue Timestamp
        run: |
          git config --global user.email "Polinka7max@gmail.com"
          git config --global user.name "Dunridge"
          git add .
          git commit -m "Add issue timestamp by $GITHUB_ACTOR"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
=======
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # TODO: learn the path to node to run the script from the sh file
      - name: Print Node.js path
        run: which node

      - name: Set execute permissions for run-metrics.sh
        run: chmod +x ./run-metrics.sh

      # - name: Set execute permissions
      #   run: chmod +x ./issue-metrics.js
      # run: chmod +x ${{ github.workspace }}/issue-metrics.js

      - name: Issue Metrics
        uses: github/issue-metrics@v2
        with:
          entryPoint: ./run-metrics.sh # TODO: configure values passed to the config
          # entryPoint: ./issue-metrics.js # error: exec ./issue-metrics.js: exec format error
          # entryPoint: ${{ github.workspace }}/issue-metrics.js # error: docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/home/runner/work/amplify/amplify/issue-metrics.js": stat /home/runner/work/amplify/amplify/issue-metrics.js: no such file or directory: unknown.
          args: '{"github-token": "${{ secrets.GH_TOKEN }}", "payload": ${{ toJson(github) }}}'
>>>>>>> d7e6f34 (passport and sesson intialize for issue 617)
