name: Spellcheck

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    name: Spellcheck

    steps:
      - uses: actions/checkout@v3
      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          files: '**/*.md **/*.txt .github/**/*.md'
          quiet: true
          dictionaries: '.github/spellcheck-dictionary.txt'
