name: Spell Check .md
on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  spellcheck:
    uses: actions/checkout@v3
    uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main
