name: Spell Check 
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Spell check
        uses: austenstone/spellchecker-cli-action-summary/.github/workflows/spellcheck.yml@main

